name: "App-Release"

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up code
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@master

    - name: Set up Nodejs
      uses: actions/setup-node@master

    - name: Clone website
      run: git clone https://github.com/yoanndelattre/Windows-Deployer-KVM-Web.git /home/runner/work/Windows-Deployer-KVM-Web

    - name: Build website
      run: cd /home/runner/work/Windows-Deployer-KVM-Web && npm install && npm run build

    - name: Move website to app
      run: mv /home/runner/work/Windows-Deployer-KVM-Web/build /home/runner/work/Windows-Deployer-KVM-App/Windows-Deployer-KVM-App/static

    - name: Get packr
      run: go get -u github.com/gobuffalo/packr/packr

    - name: Run packr
      run: cd /home/runner/work/Windows-Deployer-KVM-App/Windows-Deployer-KVM-App && export GOPATH=$HOME/go && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin && packr

    - name: Build app windows amd64
      run: GOOS=windows GOARCH=amd64 go build -o output/Windows-Deployer-Windows-x64.exe

    - name: Build app darwin amd64
      run: GOOS=darwin GOARCH=amd64 go build -o output/Windows-Deployer-Darwin-x64

    - name: Build app linux amd64
      run: GOOS=linux GOARCH=amd64 go build -o output/Windows-Deployer-Linux-x64

    - name: Build app linux arm64
      run: GOOS=linux GOARCH=arm64 go build -o output/Windows-Deployer-Linux-arm64

    - name: Build app linux arm
      run: GOOS=linux GOARCH=arm go build -o output/Windows-Deployer-Linux-arm32

    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: false
        prerelease: false
        title: "Windows-Deployer App"
        files: |
          output/Windows-Deployer-Windows-x64.exe
          output/Windows-Deployer-Darwin-x64
          output/Windows-Deployer-Linux-x64
          output/Windows-Deployer-Linux-arm64
          output/Windows-Deployer-Linux-arm32